-- =================================================================
-- ESQUEMA FITNESSFLOW PRO - SISTEMA SAAS COMPLETO (RESET & INIT)
-- =================================================================

-- ⚠️ ADVERTENCIA: Este script reiniciará las tablas listadas abajo.
-- Úsalo para configurar inicialmente o resetear la base de datos.

-- 1. LIMPIEZA PREVIA (Evitar errores "relation already exists")
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();

DROP TABLE IF EXISTS public.mensajes_chat CASCADE;
DROP TABLE IF EXISTS public.notificaciones CASCADE;
DROP TABLE IF EXISTS public.reservas CASCADE;
DROP TABLE IF EXISTS public.disponibilidad_servicios CASCADE;
DROP TABLE IF EXISTS public.servicios_entrenador CASCADE;
DROP TABLE IF EXISTS public.transacciones_financieras CASCADE;
DROP TABLE IF EXISTS public.miembros_gym CASCADE;
DROP TABLE IF EXISTS public.actividad_social CASCADE;
DROP TABLE IF EXISTS public.retos_activos CASCADE;
DROP TABLE IF EXISTS public.logros_usuario CASCADE;
DROP TABLE IF EXISTS public.logros CASCADE;
DROP TABLE IF EXISTS public.chequeos_diarios CASCADE;
DROP TABLE IF EXISTS public.horarios_clases CASCADE;
DROP TABLE IF EXISTS public.clases_disponibles CASCADE;
DROP TABLE IF EXISTS public.ejercicios_biblioteca CASCADE;
DROP TABLE IF EXISTS public.perfiles CASCADE;

-- Habilitar extensión UUID
create extension if not exists "uuid-ossp";

-- =================================================================
-- 1. MÓDULO DE USUARIOS Y PERFILES
-- =================================================================

create table public.perfiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique not null,
  nombre_completo text,
  tipo_cuenta text check (tipo_cuenta in ('user', 'gym', 'entrenador')),
  plan text check (plan in ('básico', 'premium')),
  estado_suscripcion text check (estado_suscripcion in ('trial', 'subscribed', 'expired')),
  es_miembro_gimnasio boolean default false,
  
  -- Gamificación Básica
  xp_actual int default 0,
  nivel_actual int default 1,
  titulo_actual text default 'Novato',

  -- Preferencias de Usuario
  objetivo text, 
  nivel_fitness text,
  dias_entrenamiento int,

  -- Específico de Entrenador
  profesion text,
  descripcion_profesional text,
  telefono text,
  direccion text,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.perfiles enable row level security;

create policy "Perfiles públicos visibles por todos" on public.perfiles for select using (true);
create policy "Usuarios editan su propio perfil" on public.perfiles for update using (auth.uid() = id);
create policy "Usuarios crean su propio perfil" on public.perfiles for insert with check (auth.uid() = id);

-- =================================================================
-- 2. MÓDULO DE ENTRENAMIENTO
-- =================================================================

-- Catálogo Global de Ejercicios (Solo lectura para usuarios)
create table public.ejercicios_biblioteca (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  imagen_url text,
  video_url text,
  dificultad text check (dificultad in ('Principiante', 'Intermedio', 'Avanzado')),
  categoria text, -- FUERZA, CARDIO, CORE, etc.
  equipamiento text,
  musculos_objetivo text[], -- Array de strings
  calorias_por_minuto numeric,
  es_premium boolean default false,
  instrucciones text[] -- Array de pasos
);

alter table public.ejercicios_biblioteca enable row level security;
create policy "Ejercicios visibles por todos" on public.ejercicios_biblioteca for select using (true);

-- Clases Grupales (Catálogo)
create table public.clases_disponibles (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  imagen_url text,
  video_url text,
  dificultad text,
  categoria text,
  nombre_entrenador text,
  capacidad int,
  duracion int,
  precio numeric,
  tipo_ubicacion text,
  es_demo boolean default false
);

alter table public.clases_disponibles enable row level security;
create policy "Clases visibles por todos" on public.clases_disponibles for select using (true);

-- Horarios de Clases
create table public.horarios_clases (
  id bigint generated by default as identity primary key,
  clase_id bigint references public.clases_disponibles(id) on delete cascade,
  dia_semana text,
  hora_dia text
);

alter table public.horarios_clases enable row level security;
create policy "Horarios visibles por todos" on public.horarios_clases for select using (true);

-- Chequeos Diarios (Bio-Feedback)
create table public.chequeos_diarios (
  id bigint generated by default as identity primary key,
  usuario_id uuid references public.perfiles(id) on delete cascade,
  fecha date default current_date,
  nivel_energia int,
  calidad_sueno text,
  dolor_muscular text,
  estado_animo text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.chequeos_diarios enable row level security;
create policy "Usuarios ven sus propios chequeos" on public.chequeos_diarios for select using (auth.uid() = usuario_id);
create policy "Usuarios crean sus propios chequeos" on public.chequeos_diarios for insert with check (auth.uid() = usuario_id);

-- =================================================================
-- 3. MÓDULO DE GAMIFICACIÓN
-- =================================================================

create table public.logros (
  id text primary key, -- Ej: 'first_workout'
  nombre text not null,
  descripcion text,
  icono text,
  xp_recompensa int default 0
);

alter table public.logros enable row level security;
create policy "Logros visibles por todos" on public.logros for select using (true);

create table public.logros_usuario (
  usuario_id uuid references public.perfiles(id) on delete cascade,
  logro_id text references public.logros(id) on delete cascade,
  fecha_desbloqueo timestamp with time zone default timezone('utc'::text, now()),
  primary key (usuario_id, logro_id)
);

alter table public.logros_usuario enable row level security;
create policy "Usuarios ven sus logros" on public.logros_usuario for select using (auth.uid() = usuario_id);

create table public.retos_activos (
  id text primary key,
  titulo text not null,
  descripcion text,
  objetivo numeric,
  unidad text,
  xp_recompensa int,
  fecha_limite text,
  participantes_actuales int default 0
);

alter table public.retos_activos enable row level security;
create policy "Retos visibles por todos" on public.retos_activos for select using (true);

create table public.actividad_social (
  id bigint generated by default as identity primary key,
  nombre_usuario text, 
  accion text,
  tiempo_atras text, -- Simulado para demo, o calculado
  tipo text check (tipo in ('workout', 'level_up', 'achievement')),
  likes int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

alter table public.actividad_social enable row level security;
create policy "Feed social visible por todos" on public.actividad_social for select using (true);


-- =================================================================
-- 4. MÓDULO DE GESTIÓN DE GIMNASIO (B2B)
-- =================================================================

-- Estos datos son privados para cada cuenta de tipo 'gym'

create table public.miembros_gym (
  id bigint generated by default as identity primary key,
  gym_id uuid references public.perfiles(id) on delete cascade, -- El dueño del gimnasio
  nombre text not null,
  email text,
  plan text,
  estado text check (estado in ('Al día', 'Vencido')),
  fecha_ultimo_pago date,
  fecha_registro date
);

alter table public.miembros_gym enable row level security;
create policy "Gyms ven sus miembros" on public.miembros_gym for select using (auth.uid() = gym_id);

create table public.transacciones_financieras (
  id bigint generated by default as identity primary key,
  gym_id uuid references public.perfiles(id) on delete cascade,
  fecha date,
  descripcion text,
  tipo text check (tipo in ('Ingreso', 'Gasto')),
  monto numeric,
  categoria text
);

alter table public.transacciones_financieras enable row level security;
create policy "Gyms ven sus finanzas" on public.transacciones_financieras for select using (auth.uid() = gym_id);


-- =================================================================
-- 5. SERVICIOS DE ENTRENADOR Y RESERVAS
-- =================================================================

create table public.servicios_entrenador (
  id bigint generated by default as identity primary key,
  nombre_servicio text not null,
  descripcion text,
  imagen_url text,
  video_url text,
  nombre_entrenador text,
  duracion int,
  precio numeric,
  tipo_ubicacion text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.servicios_entrenador enable row level security;
create policy "Servicios visibles por todos" on public.servicios_entrenador for select using (true);

create table public.disponibilidad_servicios (
  id bigint generated by default as identity primary key,
  servicio_id bigint references public.servicios_entrenador(id) on delete cascade,
  dia_semana text,
  hora_inicio text
);

alter table public.disponibilidad_servicios enable row level security;
create policy "Disponibilidad visible por todos" on public.disponibilidad_servicios for select using (true);

create table public.reservas (
  id bigint generated by default as identity primary key,
  usuario_id uuid references public.perfiles(id),
  clase_id bigint references public.clases_disponibles(id),
  servicio_id bigint references public.servicios_entrenador(id),
  estado text default 'pendiente_confirmacion',
  fecha_programada text,
  hora_programada text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.reservas enable row level security;
create policy "Usuarios gestionan sus reservas" on public.reservas for all using (auth.uid() = usuario_id);


-- =================================================================
-- DATOS SEMILLA (MIGRACIÓN DE DATOS LOCALES)
-- =================================================================

-- 1. Insertar Ejercicios (Desde src/data/exercises.ts)
INSERT INTO public.ejercicios_biblioteca (nombre, descripcion, imagen_url, video_url, dificultad, categoria, equipamiento, musculos_objetivo, calorias_por_minuto, es_premium, instrucciones) VALUES
('Bicicleta Estática', 'Ejercicio de cardio de bajo impacto excelente para las piernas.', 'https://images.pexels.com/photos/3760968/pexels-photo-3760968.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/8555431/8555431-sd_640_360_25fps.mp4', 'Principiante', 'CARDIO', 'Bicicleta estática', ARRAY['Cuádriceps', 'Pantorrillas'], 10, false, ARRAY['Ajusta la altura', 'Mantén espalda recta', 'Pedalea constante']),
('Burpees', 'Ejercicio de alta intensidad que combina fuerza y cardio.', 'https://images.pexels.com/photos/6456137/pexels-photo-6456137.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/4761427/4761427-sd_640_360_25fps.mp4', 'Avanzado', 'CUERPO COMPLETO', 'Peso corporal', ARRAY['Core', 'Pecho', 'Piernas'], 15, true, ARRAY['De pie a cuclillas', 'Plancha', 'Flexión', 'Salto']),
('Correr en Cinta', 'Ejercicio cardiovascular de bajo impacto.', 'https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/5319759/5319759-sd_640_360_25fps.mp4', 'Principiante', 'CARDIO', 'Cinta de correr', ARRAY['Cardio'], 12, false, ARRAY['Selecciona velocidad', 'Postura erguida']),
('Curl de Bíceps', 'Ejercicio de aislamiento para bíceps.', 'https://images.pexels.com/photos/1431282/pexels-photo-1431282.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/4761426/4761426-sd_640_360_25fps.mp4', 'Principiante', 'FUERZA', 'Mancuernas', ARRAY['Bíceps', 'Brazos'], 5, true, ARRAY['Brazos extendidos', 'Flexiona codos', 'Baja controlado']),
('Remo con Barra', 'Ejercicio compuesto para espalda.', 'https://images.pexels.com/photos/949126/pexels-photo-949126.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/8558238/8558238-sd_640_360_25fps.mp4', 'Intermedio', 'FUERZA', 'Barra', ARRAY['Espalda', 'Bíceps'], 8, false, ARRAY['Inclina torso', 'Tira barra al pecho', 'Aprieta espalda']),
('Sentadilla con Barra', 'El rey de los ejercicios de piernas.', 'https://images.pexels.com/photos/116077/pexels-photo-116077.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/3209191/3209191-sd_640_360_25fps.mp4', 'Avanzado', 'FUERZA', 'Barra', ARRAY['Piernas', 'Glúteos'], 10, false, ARRAY['Barra en trapecios', 'Espalda recta', 'Baja profundo', 'Empuja con talones']),
('Peso Muerto', 'Ejercicio de cuerpo completo.', 'https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/8558238/8558238-sd_640_360_25fps.mp4', 'Avanzado', 'FUERZA', 'Barra', ARRAY['Piernas', 'Espalda'], 12, false, ARRAY['Espalda recta', 'Barra pegada', 'Empuja con piernas']),
('Press de Banca', 'Fundamental para pectoral.', 'https://images.pexels.com/photos/3837464/pexels-photo-3837464.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/3209191/3209191-sd_640_360_25fps.mp4', 'Intermedio', 'FUERZA', 'Barra y banco', ARRAY['Pecho', 'Hombros'], 7, true, ARRAY['Pies en suelo', 'Baja al pecho', 'Empuja explosivo']);

-- 2. Insertar Logros (Desde src/data/progress.ts)
INSERT INTO public.logros (id, nombre, descripcion, icono, xp_recompensa) VALUES
('first_workout', 'Rompiendo el Hielo', 'Completa tu primer entrenamiento.', '🎉', 100),
('streak_5', 'Imparable', 'Completa 5 días de entrenamiento en una semana.', '🔥', 500),
('one_month', 'Constancia de Acero', 'Entrena durante un mes completo.', '🗓️', 1000),
('first_pr', 'Superando Límites', 'Rompe tu primer récord personal.', '🚀', 300),
('10k_volume', 'Levantador Novato', 'Levanta 10,000 kg en total.', '💪', 200),
('50_workouts', 'Maratonista de Hierro', 'Completa 50 entrenamientos.', '🏅', 1500),
('100k_volume', 'Titán de Hierro', 'Levanta 100,000 kg en total.', '🌋', 2000),
('three_months', 'Consistencia de Élite', 'Entrena de forma consistente por 3 meses.', '💎', 3000);

-- 3. Insertar Retos Activos (Desde src/data/gamification.ts)
INSERT INTO public.retos_activos (id, titulo, descripcion, objetivo, unidad, xp_recompensa, fecha_limite, participantes_actuales) VALUES
('1', 'Semana de Fuego', 'Completa 4 entrenamientos esta semana.', 4, 'sesiones', 500, 'Domingo', 124),
('2', 'Corredor Matutino', 'Acumula 15km corriendo antes de las 9 AM.', 15, 'km', 300, '30 Jun', 56);

-- 4. Insertar Actividad Social (Desde src/data/gamification.ts)
INSERT INTO public.actividad_social (nombre_usuario, accion, tiempo_atras, tipo, likes) VALUES
('Diego V.', 'rompió su PR en Peso Muerto (140kg)', '2h', 'workout', 12),
('Sofia G.', 'subió a Nivel 5: "Atleta"', '4h', 'level_up', 24),
('Mateo H.', 'completó el reto "Semana de Fuego"', '5h', 'achievement', 8),
('Laura M.', 'finalizó clase de Yoga Flow', '6h', 'workout', 5);

-- 5. Insertar Clases y Servicios (Como antes)
INSERT INTO public.clases_disponibles (nombre, descripcion, imagen_url, video_url, dificultad, categoria, nombre_entrenador, capacidad, duracion, precio, tipo_ubicacion, es_demo)
VALUES 
('CrossFit WOD', 'Entrenamiento funcional de alta intensidad.', 'https://images.pexels.com/photos/1552242/pexels-photo-1552242.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/8558238/8558238-sd_640_360_25fps.mp4', 'Avanzado', 'CrossFit', 'Diego Valencia', 12, 60, 15000, 'Gimnasio', true),
('Hatha Yoga Flow', 'Clase de yoga suave.', 'https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/3192279/3192279-sd_640_360_25fps.mp4', 'Principiante', 'Yoga', 'Laura Morales', 15, 60, 0, 'Gimnasio', true),
('Spinning RPM', 'Clase de ciclismo indoor.', 'https://images.pexels.com/photos/39308/runners-silhouettes-athletes-fitness-39308.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/8555431/8555431-sd_640_360_25fps.mp4', 'Intermedio', 'Spinning', 'Carlos Rojas', 20, 50, 12000, 'Gimnasio', true);

INSERT INTO public.horarios_clases (clase_id, dia_semana, hora_dia) 
SELECT id, 'Lunes', '18:00' FROM public.clases_disponibles WHERE nombre = 'CrossFit WOD';

INSERT INTO public.servicios_entrenador (nombre_servicio, descripcion, imagen_url, video_url, nombre_entrenador, duracion, precio, tipo_ubicacion)
VALUES
('Sesión de Entrenamiento Personalizado', 'Una sesión de 60 minutos uno a uno.', 'https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/4761426/4761426-sd_640_360_25fps.mp4', 'Juan Valdez', 60, 50000, 'Gimnasio'),
('Asesoría Nutricional Fitness', 'Consulta de 45 minutos.', 'https://images.pexels.com/photos/1128678/pexels-photo-1128678.jpeg?auto=compress&cs=tinysrgb&w=600', 'https://videos.pexels.com/video-files/3195968/3195968-sd_640_360_25fps.mp4', 'Juan Valdez', 45, 40000, 'Virtual');


-- 6. Trigger Autocreate Profile
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.perfiles (id, email, nombre_completo, tipo_cuenta, plan, estado_suscripcion)
  values (
    new.id, 
    new.email, 
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', 'Usuario Nuevo'),
    coalesce(new.raw_user_meta_data->>'account_type', 'user'),
    coalesce(new.raw_user_meta_data->>'plan', 'básico'),
    'trial'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
